### ISSUE TITLE
District Overall Average Calculating Wrong

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre-Assessments#15]
When calculating districts overall average, the formula is wrong.

For example: I'm looking at College Prep Math Quarter 2 (7th Grade). It shows

- 758 students (this is correct)
- 25% (this is incorrect - it should be 40%).

CSV export gives 40%.

Also seems to affect calculations of teachers. Basically lowering averages for teachers.

**Comment by wilso199** [comment]
@zjvv This issue should be resolved. Let us know if you see any further discrepancies.
