### ISSUE TITLE
Issue pulling teacher results

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre-Assessments#17]
When viewing results on an assessment:

1. Select "View By Building"
2. Select the building (ie "Wilson")
3. Select a teacher who teaches the course

I get a box with short stats. 

**The Issue**
When you click "view details" of the teacher, it does not show any students. It shows lots of entries (with having not taken the test).

Results are available for downloading all results AND viewing results by teacher correctly.

**Comment by hcsdrose** [comment]
@zjvv can you send us an example of specific data to support@abre.io?

**Comment by zjvv** [comment]
Closed.
