### ISSUE TITLE
Viewing all Student Results

### ISSUE THREAD

**Issue by zjvv** [abreio/Abre-Assessments#18]
I've had a number of teachers contact me with not being able to see all results of their students (they're just seeing them as in progress). I will see them in the classroom later today, but wanted to put this on your radar as it's bubbling up.

> I have a few students who I am not able to see their results when giving an assessment.  Previously I could review their results when "Viewing all Results",, their names appeared with their emails but not with their enrolled class.  With my most recent assignment no data comes up under view all.

I've verified with the teacher that this is still an issue after the update from yesterday.

**Comment by wilso199** [comment]
Closing: Emails need to be associated with the students for teachers to be able to see students results.
